### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x37 and 45x16)

### ISSUE THREAD

**Issue by stevenguo001** [CORE-Robotics-Lab/GrAMMI#1]
When I was reproducing your code, I found that your dataset labeling was messy, sometimes it reads from the dataset directory, sometimes it reads from the grammi_dataset directory, I manually changed the relevant paths.  However, when the code in run_multiple.py runs to the last line of the run_categorical_info function, an error occurs, and I can't find a solution even after tracing the code back to the source, can you help me see where the problem is?
The following is the error message：

grammi_datasets/prisoner_datasets/3_detect/train
logs/0/3_detect/categorical/20240321-1444/config.yaml
Training model: categorical_mi
Dataset: 3_detect
101 logs/0/3_detect/categorical/20240321-1444/best.pth

Training on Padded Dataset w/ prisoner
Training on Padded Dataset w/ prisoner
0%| | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/mnt/workspace/GrAMMI/run_multiple.py", line 196, in <module>
run_categorical_mutual_info(timestep, dataset_paths, base_log_directory)
File "/mnt/workspace/GrAMMI/run_multiple.py", line 80, in run_categorical_mutual_info
main_config_mutual_info(config)
File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 314, in main_config_mutual_info
train(seed,
File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 171, in train
post = posterior(*posterior_input)
File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 55, in forward
x = self.leaky_relu(self.h1(x))
File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
return F.linear(input, self.weight, self.bias)
File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x37 and 45x16)

**Comment by xunil17** [comment]
Hi Steven,

Thanks for taking interest in our codebase and we will get back to you asap to debug the issues, thanks!

**Comment by xunil17** [comment]
Hi Steven, 

I've pushed an update to the codebase that should solve this issue. The problem was that previously, the posterior network during finetuning was hardcoded for GNN (input_dim should be 45) and non-GNN models (input_dim should be 37). Given that you've already trained the models without mutual information, you can comment out the `run_categorical(timestep, dataset_paths, base_log_directory)` and just run `run_categorical_mutual_info(timestep, dataset_paths, base_log_directory)` in `run_multiple.py`. 

Please pull the latest commit and let me know if it fixes your issue!

**Comment by stevenguo001** [comment]
Thank you for the timely response, it means a lot to me. I will give it a try and hope to achieve the desired results!

**Comment by stevenguo001** [comment]
I noticed you have a smuggler_paper_2 _helo _60 folder in your path, but the dataset I downloaded doesn't have this folder, but there is a smuggler_paper_3 folder, are these two folders the same?

**Comment by stevenguo001** [comment]
And I have tried another time, the same issue still occurred.

**Comment by xunil17** [comment]
Sorry about that, I've corrected the naming error and the two paths for smuggler should be `2_helo_40` and `3_helo_40`. 

Can you paste your error message? Even if its the same error it will be useful to see the error traceback so I can pinpoint where in the code it is breaking for you. Thanks!

**Comment by xunil17** [comment]
Hello, is there anything else I can help with? Otherwise I will close this issue, thanks!

**Comment by stevenguo001** [comment]
Sorry, my GitHub didn't alert me, and I'm only now seeing your reply. I'm very sorry! Here is the error report.

(grammi) root@dsw-342101-5976b9b6b4-wxmh5:/mnt/workspace/GrAMMI# python run_multiple.py
grammi_datasets/prisoner_datasets/3_detect/train
logs/0/3_detect/categorical/20240321-1444/config.yaml
Training model:  categorical_mi
Dataset:  3_detect
101 logs/0/3_detect/categorical/20240321-1444/best.pth


Training on Padded Dataset w/ prisoner
Training on Padded Dataset w/ prisoner
  0%|                                                                                                              | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/workspace/GrAMMI/run_multiple.py", line 191, in <module>
    run_categorical_mutual_info(timestep, dataset_paths, base_log_directory)
  File "/mnt/workspace/GrAMMI/run_multiple.py", line 80, in run_categorical_mutual_info
    main_config_mutual_info(config)
  File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 314, in main_config_mutual_info
    train(seed,
  File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 171, in train
    post = posterior(*posterior_input)
  File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/GrAMMI/train_mi_gaussian_posterior_categorical.py", line 55, in forward
    x = self.leaky_relu(self.h1(x))
  File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/grammi/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x37 and 45x16)

**Comment by xunil17** [comment]
Hi, thanks for the info. Have you pulled the latest commit including all changes to `train_mi_gaussian_posterior_categorical.py` and the models folder? I see your error for `post = posterior(*posterior_input)` is on line 151 but in the new code, it is on line 158 or line 211. Another way to check if you have pulled the new code is if the posterior now has the in_dim as shown here in line 94: `posterior = PosteriorMLP(in_dim=model.encoder_output_dim, hidden_dim=16, out_dim=num_gaussians).to(device)`. Alternatively, you can also just hardcode the in_dim to 37 manually but you will have to change back to 45 if you are training the GNN models.

**Comment by stevenguo001** [comment]
OK! I'll check them out and feedback to you ASAP! Thanks for your help!
